# _quarto.yml
# This configuration creates the base for whole of the project which is of
# `type: website` and will be deployed (one-day) to hrmnjt.dev. As of now, this
# is an experiment and we will know if this passes or fails soon.

project:
  type: website

website:
  title: "hrmnjt.dev"
  navbar:
    # keeping a dark background to have minimal profile
    background: dark
    # removing search for time being to simplify the UI options
    search: false
  draft-mode: unlinked
    
format:
  html:
    # simplest dark theme after trying out a few
    theme: darkly
    mainfont: 'ui-monospace, "SF Mono", "Cascadia Mono", "Segoe UI Mono", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace'
    # fontsize: 0.95em
    linestretch: 1.75
    toc: true

# adding this option because I want to freeze runs locally before pushing
# content to GH pages
execute:
  freeze: auto
